-- Add up migration script here
start transaction;

insert into beat_saber_versions (ver) values ('0.10.1');
insert into beat_saber_versions (ver) values ('0.10.2');
insert into beat_saber_versions (ver) values ('0.10.2-p1');
insert into beat_saber_versions (ver) values ('0.11.0-b1');
insert into beat_saber_versions (ver) values ('0.11.0');
insert into beat_saber_versions (ver) values ('0.11.1');
insert into beat_saber_versions (ver) values ('0.11.2');
insert into beat_saber_versions (ver) values ('0.12.0');
insert into beat_saber_versions (ver) values ('0.12.0-p1');
insert into beat_saber_versions (ver) values ('0.12.1');
insert into beat_saber_versions (ver) values ('0.12.2');
insert into beat_saber_versions (ver) values ('0.13.0');
insert into beat_saber_versions (ver) values ('0.13.0-p1');
insert into beat_saber_versions (ver) values ('0.13.1');
insert into beat_saber_versions (ver) values ('0.13.2');
insert into beat_saber_versions (ver) values ('1.0.0');
insert into beat_saber_versions (ver) values ('1.0.1');
insert into beat_saber_versions (ver) values ('1.1.0');
insert into beat_saber_versions (ver) values ('1.1.0-p1');
insert into beat_saber_versions (ver) values ('1.2.0');
insert into beat_saber_versions (ver) values ('1.3.0');
insert into beat_saber_versions (ver) values ('1.4.0');
insert into beat_saber_versions (ver) values ('1.4.2');
insert into beat_saber_versions (ver) values ('1.5.0');
insert into beat_saber_versions (ver) values ('1.6.0');
insert into beat_saber_versions (ver) values ('1.6.1');
insert into beat_saber_versions (ver) values ('1.6.2');
insert into beat_saber_versions (ver) values ('1.7.0');
insert into beat_saber_versions (ver) values ('1.8.0');
insert into beat_saber_versions (ver) values ('1.9.0');
insert into beat_saber_versions (ver) values ('1.9.1');
insert into beat_saber_versions (ver) values ('1.10.0');
insert into beat_saber_versions (ver) values ('1.11.0');
insert into beat_saber_versions (ver) values ('1.11.1');
insert into beat_saber_versions (ver) values ('1.12.1');
insert into beat_saber_versions (ver) values ('1.12.2');
insert into beat_saber_versions (ver) values ('1.13.0');
insert into beat_saber_versions (ver) values ('1.13.2');
insert into beat_saber_versions (ver) values ('1.13.4');
insert into beat_saber_versions (ver) values ('1.13.5');
insert into beat_saber_versions (ver) values ('1.14.0');
insert into beat_saber_versions (ver) values ('1.15.0');
insert into beat_saber_versions (ver) values ('1.16.0');
insert into beat_saber_versions (ver) values ('1.16.1');
insert into beat_saber_versions (ver) values ('1.16.2');
insert into beat_saber_versions (ver) values ('1.16.3');
insert into beat_saber_versions (ver) values ('1.16.4');
insert into beat_saber_versions (ver) values ('1.17.0');
insert into beat_saber_versions (ver) values ('1.17.1');
insert into beat_saber_versions (ver) values ('1.18.0');
insert into beat_saber_versions (ver) values ('1.18.1');
insert into beat_saber_versions (ver) values ('1.18.2');
insert into beat_saber_versions (ver) values ('1.18.3');
insert into beat_saber_versions (ver) values ('1.19.0');
insert into beat_saber_versions (ver) values ('1.19.1');
insert into beat_saber_versions (ver) values ('1.20.0');
insert into beat_saber_versions (ver) values ('1.21.0');
insert into beat_saber_versions (ver) values ('1.22.0');
insert into beat_saber_versions (ver) values ('1.22.1');
insert into beat_saber_versions (ver) values ('1.23.0');
insert into beat_saber_versions (ver) values ('1.24.0');
insert into beat_saber_versions (ver) values ('1.24.1');
insert into beat_saber_versions (ver) values ('1.25.0');
insert into beat_saber_versions (ver) values ('1.25.1');
insert into beat_saber_versions (ver) values ('1.26.0');
insert into beat_saber_versions (ver) values ('1.27.0');
insert into beat_saber_versions (ver) values ('1.28.0');
insert into beat_saber_versions (ver) values ('1.29.0');
insert into beat_saber_versions (ver) values ('1.29.1');
insert into beat_saber_versions (ver) values ('1.29.4');
insert into beat_saber_versions (ver) values ('1.30.0');
insert into beat_saber_versions (ver) values ('1.30.2');
insert into beat_saber_versions (ver) values ('1.31.0');

insert into categories (name, description) values ('core', 'Mods that only depend on other core mods.');
insert into categories (name, description) values ('libraries', 'Mods that are used by other mods.');
insert into categories (name, description) values ('cosmetic', 'Mods that affect the appearance of the game.');
insert into categories (name, description) values ('gameplay', 'Mods that affect gameplay.');
insert into categories (name, description) values ('leaderboards', 'Mods that affect leaderboards.');
insert into categories (name, description) values ('lighting', 'Mods that affect lighting.');
insert into categories (name, description) values ('multiplayer', 'Mods that change online play.');
insert into categories (name, description) values ('accessibility', 'Mods that affect accessibility.');
insert into categories (name, description) values ('practice', 'Mods that are used for practice.');
insert into categories (name, description) values ('streaming', 'Mods that affect live streams.');
insert into categories (name, description) values ('text', 'Mods that change how text is displayed.');
insert into categories (name, description) values ('tweaks', 'Mods that tweak the gameplay experience.');
insert into categories (name, description) values ('ui', 'Mods that affect the ui.');
insert into categories (name, description) values ('other', 'Mods that do not fit into other categories.');

commit;